version: "3.7"

x-base: &base
  image: ghcr.io/t7tran/chatwoot:3.3.1
  env_file: .env ## Change this file for customized env variables
  volumes:
    - chatwoot:/app/storage

services:
  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    environment:
      CW_ROLE: web
      CW_ACCOUNT_NAME: Chatwoot Demo
      CW_ACCOUNT_DOMAIN: localhost
      CW_ACCOUNT_EMAIL: support@yourcompany.com
      CW_ADMIN_EMAIL: admin@yourcompany.com
      CW_ADMIN_PASSWORD: sup3rP@ss
      CW_ADMIN_ACCESS_TOKEN: sup3rT0ken2
      CW_INSTALLATION_NAME: name
      CW_BRAND_NAME: brand
      CW_WEB_WIDGET: "true"
      CW_WEB_WIDGET_NAME: Demo Widget
      CW_WEB_WIDGET_SITE_URL: http://localhost:8080
      CW_WEB_WIDGET_SITE_TOKEN: token11
      CW_WEB_WIDGET_HMAC_TOKEN: token22
  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      CW_ROLE: worker

  postgres:
    image: ghcr.io/t7tran/postgres:14.8.0
    restart: always
    read_only: true
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    tmpfs:
      - /var/run/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7.2.0-alpine
    restart: always
    read_only: true
    user: 999:1000
    command: ["sh", "-c", 'redis-server --requirepass "$REDIS_PASSWORD"']
    env_file: .env
    volumes:
      - redis:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    logging:
      driver: "none" # disable saving logs
    ports:
      - 8025:8025 # web ui
    #- 1025:1025 # smtp server

volumes:
  redis:
    labels:
      - "keep=true"
      - "app=chatwoot"
  postgres:
    labels:
      - "keep=true"
      - "app=chatwoot"
  chatwoot:
    labels:
      - "keep=true"
      - "app=chatwoot"
